{"status": "broken", "uuid": "7a7505f3-ddf1-4fd6-9e22-9caf98cdbff1", "labels": [{"name": "feature", "value": "login"}, {"name": "suite", "value": "test_sample"}, {"name": "host", "value": "LAPTOP-1DMUQ9HH"}, {"name": "thread", "value": "9212-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython2"}, {"name": "package", "value": "test_sample"}], "stop": 1590717294336, "testCaseId": "7b1b40993d44d933eaa4e532f23cb10a", "historyId": "98e8177db66798f6072f43d67e9a0b3b", "start": 1590717294336, "fullName": "test_sample#test_1", "statusDetails": {"message": "AttributeError: type object 'api_test' has no attribute 'uri'", "trace": "@allure.feature('login')\n    def test_1():\n>       roleinfos=test01.login()\n\ntest_sample.py:27: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <case.monitoring.monitoring object at 0x0000000004A211D0>\n\n    def login(self):\n        url = '/user-check'\n        # m = hashlib.md5()\n        # m.update(password)\n>       headers = {\"Accept\": \"application/json, text/plain, */*\",  \"Origin\": test.uri, \"Referer\": test.uri}\nE       AttributeError: type object 'api_test' has no attribute 'uri'\n\n..\\case\\monitoring.py:9: AttributeError"}, "name": "test_1"}