{"status": "broken", "uuid": "85a1f158-5210-4216-bcb2-7b5883335666", "labels": [{"name": "feature", "value": "login"}, {"name": "suite", "value": "test_sample"}, {"name": "host", "value": "LAPTOP-1DMUQ9HH"}, {"name": "thread", "value": "2360-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython2"}, {"name": "package", "value": "test_sample"}], "stop": 1590717203257, "testCaseId": "7b1b40993d44d933eaa4e532f23cb10a", "historyId": "98e8177db66798f6072f43d67e9a0b3b", "start": 1590717203257, "fullName": "test_sample#test_1", "statusDetails": {"message": "AttributeError: type object 'api_test' has no attribute 'uri'", "trace": "@allure.feature('login')\n    def test_1():\n>       roleinfos=test01.login()\n\ntest_sample.py:27: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <case.monitoring.monitoring object at 0x00000000047243C8>\n\n    def login(self):\n        url = '/user-check'\n        # m = hashlib.md5()\n        # m.update(password)\n>       headers = {\"Accept\": \"application/json, text/plain, */*\",  \"Origin\": test.uri, \"Referer\": test.uri}\nE       AttributeError: type object 'api_test' has no attribute 'uri'\n\n..\\case\\monitoring.py:9: AttributeError"}, "name": "test_1"}